.\" Copyright \[co] 2007 Jaakko Hyv\[:a]tti
.TH PICPROG 1 "picprog 1.9" "29 Oct 2007"
.SH NAME
picprog \- Microchip PIC programmer for the serial port device
.SH SYNOPSIS
.B picprog
.B \-\-quiet
.B \-\-warranty
.B \-\-copying
.B \-\-help
.B \-\-device
.I chiptype
.B \-d
.I chiptype
.B \-\-pic\-serial\-port
.I device
.B \-p
.I device
.B \-\-input\-hexfile
.I path
.B \-i
.I path
.B \-\-output\-hexfile
.I path
.B \-o
.I path
.B \-\-ihx32
.B \-\-ihx16
.B \-\-ihx8m
.B \-\-cc\-hexfile
.I path
.B \-c
.I path
.B \-\-skip\-ones
.B \-\-erase
.B \-\-burn
.B \-\-force\-calibration
.B \-\-nordtsc
.B \-\-rdtsc
.B \-\-slow
.B \-\-reboot
.B \-q \-h \-?
.SH ENVIRONMENT
.B PIC_DEVICE
.B PIC_PORT
.SH DESCRIPTION
See <URL:http://www.iki.fi/hyvatti/pic/picprog.html>.
.SH OPTIONS
See <URL:http://www.iki.fi/hyvatti/pic/picprog.html>.
.SH AUTHOR
Jaakko Hyv\[:a]tti
.LP
Jaakko.Hyvatti@iki.fi, http://www.iki.fi/hyvatti/
